[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool]
  [tool.commitizen]
  version = "0.0.0"
  version_files = ["pyproject.toml:version"]
  major_version_zero = true

  [tool.poetry]
  name = "Template Repo"
  version = "0.0.0"
  description = "Template Repository for ScribeMD"
  authors = ["Kurt von Laven <kurt.von.laven@gmail.com>"]
  license = "MIT"

  [tool.poetry.dependencies]
  # Keep in sync with .pre-commit-config.yaml and .tool-versions.
  python = "3.11.0"

  [tool.poetry.dev-dependencies]
  commitizen = "2.37.0" # Keep in sync with .pre-commit-config.yaml.
  pre-commit = "2.20.0"
